# Discovered model candidates — copy entries into app/priorities/aliases.py

NEW_MODELS: dict[str, list[tuple[str, str]]] = {
    "auto": [
        ("groq",          "meta-llama/llama-4-scout-17b-16e-instruct"),
        ("groq",          "meta-llama/llama-prompt-guard-2-86m"),
        ("groq",          "qwen/qwen3-32b"),
        ("groq",          "groq/compound"),
        ("groq",          "meta-llama/llama-prompt-guard-2-22m"),
        ("google",        "gemma-3-27b-it"),
        ("google",        "gemma-3n-e4b-it"),
        ("google",        "gemma-3n-e2b-it"),
        ("google",        "gemma-4-31b-it"),
        ("openrouter",    "openrouter/elephant-alpha"),
        ("openrouter",    "google/gemma-4-26b-a4b-it:free"),
        ("openrouter",    "google/gemma-4-31b-it:free"),
        ("openrouter",    "nvidia/nemotron-3-super-120b-a12b:free"),
        ("openrouter",    "openai/gpt-oss-120b:free"),
        ("openrouter",    "openai/gpt-oss-20b:free"),
        ("openrouter",    "google/gemma-3n-e4b-it:free"),
        ("nvidia",        "google/gemma-3-27b-it"),
        ("nvidia",        "google/gemma-3n-e2b-it"),
        ("nvidia",        "google/gemma-3n-e4b-it"),
        ("nvidia",        "meta/llama-3.2-11b-vision-instruct"),
        ("nvidia",        "meta/llama-4-maverick-17b-128e-instruct"),
        ("nvidia",        "meta/llama-guard-4-12b"),
        ("nvidia",        "microsoft/phi-4-multimodal-instruct"),
        ("nvidia",        "minimaxai/minimax-m2.5"),
        ("nvidia",        "mistralai/ministral-14b-instruct-2512"),
        ("nvidia",        "mistralai/mistral-medium-3-instruct"),
        ("nvidia",        "mistralai/mistral-nemotron"),
        ("nvidia",        "mistralai/mixtral-8x22b-instruct-v0.1"),
        ("nvidia",        "mistralai/mixtral-8x7b-instruct-v0.1"),
        ("nvidia",        "nvidia/gliner-pii"),
        ("nvidia",        "nvidia/ising-calibration-1-35b-a3b"),
        ("nvidia",        "nvidia/llama-3.3-nemotron-super-49b-v1"),
        ("nvidia",        "nvidia/nemotron-3-content-safety"),
        ("nvidia",        "nvidia/nemotron-3-super-120b-a12b"),
        ("nvidia",        "nvidia/nemotron-3-super-120b-a12b"),
        ("nvidia",        "nvidia/nemotron-nano-12b-v2-vl"),
        ("nvidia",        "qwen/qwen3-next-80b-a3b-instruct"),
        ("nvidia",        "qwen/qwen3-next-80b-a3b-thinking"),
        ("nvidia",        "sarvamai/sarvam-m"),
        ("nvidia",        "stockmark/stockmark-2-100b-instruct"),
    ],
    "coding": [
        ("nvidia",        "mistralai/devstral-2-123b-instruct-2512"),
        ("nvidia",        "qwen/qwen3-coder-480b-a35b-instruct"),
    ],
    "fast": [
        ("groq",          "groq/compound-mini"),
        ("groq",          "allam-2-7b"),
        ("google",        "gemma-3-1b-it"),
        ("google",        "gemini-flash-lite-latest"),
        ("google",        "gemini-2.5-flash-lite"),
        ("google",        "gemini-3.1-flash-lite-preview"),
        ("openrouter",    "liquid/lfm-2.5-1.2b-instruct:free"),
        ("nvidia",        "google/gemma-2-2b-it"),
        ("nvidia",        "google/gemma-3-4b-it"),
        ("nvidia",        "meta/llama-3.1-8b-instruct"),
        ("nvidia",        "meta/llama-3.2-1b-instruct"),
        ("nvidia",        "meta/llama-3.2-3b-instruct"),
        ("nvidia",        "mistralai/mistral-7b-instruct-v0.3"),
        ("nvidia",        "mistralai/mistral-small-4-119b-2603"),
        ("nvidia",        "nvidia/llama-3.1-nemoguard-8b-content-safety"),
        ("nvidia",        "nvidia/llama-3.1-nemoguard-8b-topic-control"),
        ("nvidia",        "nvidia/llama-3.1-nemotron-nano-8b-v1"),
        ("nvidia",        "nvidia/llama-3.1-nemotron-nano-vl-8b-v1"),
        ("nvidia",        "nvidia/llama-3.1-nemotron-safety-guard-8b-v3"),
        ("nvidia",        "nvidia/nemotron-content-safety-reasoning-4b"),
        ("nvidia",        "nvidia/nemotron-mini-4b-instruct"),
        ("nvidia",        "nvidia/riva-translate-4b-instruct-v1.1"),
        ("nvidia",        "upstage/solar-10.7b-instruct"),
    ],
    "smart": [
        ("openrouter",    "arcee-ai/trinity-large-preview:free"),
        ("nvidia",        "abacusai/dracarys-llama-3.1-70b-instruct"),
        ("nvidia",        "meta/llama-3.1-405b-instruct"),
        ("nvidia",        "meta/llama-3.1-70b-instruct"),
        ("nvidia",        "meta/llama-3.2-90b-vision-instruct"),
        ("nvidia",        "mistralai/mistral-large-3-675b-instruct-2512"),
        ("nvidia",        "moonshotai/kimi-k2-instruct"),
        ("nvidia",        "moonshotai/kimi-k2-instruct-0905"),
        ("nvidia",        "nvidia/llama-3.1-nemotron-ultra-253b-v1"),
    ],
}
